# Generated by Django 4.2.5 on 2024-03-10 09:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('GENDER', models.CharField(choices=[('S', 'Student'), ('C', 'Coordinator'), ('T-O', 'TNP-Office')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('MIDDLE_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PRN', models.PositiveIntegerField(unique=True)),
                ('DOB', models.DateField()),
                ('GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('PERSONAL_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('AGE', models.PositiveIntegerField()),
                ('MOBILE_NO', models.PositiveIntegerField()),
                ('ALT_Mobile_NO', models.PositiveIntegerField()),
                ('LOCAL_ADDRS', models.CharField(max_length=255)),
                ('PERM_ADDRS', models.CharField(max_length=255)),
                ('Native_Place', models.CharField(max_length=255)),
                ('X_Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Xth_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('X_year_of_passing', models.PositiveIntegerField()),
                ('X_board', models.CharField(max_length=255)),
                ('XIIth_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('XII_Percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('XII_year_of_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('XII_board', models.CharField(blank=True, max_length=255, null=True)),
                ('Diploma_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Diploma_Firstyear_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('Diploma_Secondyear_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('Diploma_Thirdyear_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('Diploma_year_of_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('Diploma_college', models.CharField(blank=True, max_length=255, null=True)),
                ('Diploma_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('Admission_Type', models.CharField(max_length=255)),
                ('YEAR', models.CharField(choices=[('3rd year', '3rd year'), ('Btech', 'Btech')], max_length=10)),
                ('Engg_year_of_passing', models.PositiveIntegerField()),
                ('SEM_1_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem1_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_2_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem2_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_3_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem3_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_4_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem4_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_5_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem5_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_6_sgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sem6_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_7_sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sem7_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('SEM_8_sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sem8_marksheet', models.FileField(blank=True, null=True, upload_to='images/documents/')),
                ('AVG_TILL_SEM_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('AVG_TILL_SEM_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Live_backlogs', models.PositiveIntegerField()),
                ('Dead_backlogs', models.CharField(max_length=255)),
                ('Year_gap', models.CharField(max_length=255)),
                ('Preference_1', models.CharField(max_length=255)),
                ('Preference_2', models.CharField(max_length=255)),
                ('Preference_3', models.CharField(max_length=255)),
                ('Placed', models.CharField(max_length=255)),
                ('Profile_photo', models.ImageField(upload_to='images/profiles/')),
                ('password', models.CharField(max_length=128)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.PositiveIntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PERSONAL_EMAIL', models.EmailField(max_length=254)),
                ('C_ID', models.PositiveIntegerField(unique=True)),
                ('INSTITUTE', models.CharField(max_length=255)),
                ('PROFILE_PHOTO', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
