# Generated by Django 4.2.5 on 2024-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='GENDER',
            new_name='user_type',
        ),
    ]
