# Generated by Django 4.2.5 on 2024-03-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_gender_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
