# Generated by Django 4.2.5 on 2024-03-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='YEAR',
        ),
        migrations.AddField(
            model_name='student',
            name='Pass_out_Year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2024', max_length=10),
        ),
    ]
