# Generated by Django 4.2.5 on 2024-03-19 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/Coordinator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_Firstyear_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_Secondyear_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Diploma_Thirdyear_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/diploma3'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='XIIth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/12th'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Xth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/10th'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem1_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem2_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem3_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='images/documents/Sem3'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem4_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem4'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem5_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem5'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem6_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem6'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem7_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem7'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem8_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/Sem8'),
        ),
        migrations.CreateModel(
            name='TNPOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_ID', models.PositiveIntegerField(unique=True)),
                ('NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.PositiveIntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PERSONAL_EMAIL', models.EmailField(max_length=254)),
                ('PROFILE_PHOTO', models.ImageField(blank=True, null=True, upload_to='images/profiles/tnp')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
