# Generated by Django 4.2.5 on 2024-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_coordinator_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='C_ID',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='tnpoffice',
            name='T_ID',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
