# Generated by Django 4.2.5 on 2024-03-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_alter_activity_reference_no'),
        ('users', '0014_alter_coordinator_c_id_alter_tnpoffice_t_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.drive')),
            ],
            options={
                'unique_together': {('title', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.activity')),
            ],
            options={
                'unique_together': {('title', 'student')},
            },
        ),
    ]
