# Generated by Django 4.2.5 on 2024-03-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_alter_activity_reference_no'),
        ('users', '0015_driveapplication_activityapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityapplication',
            old_name='student',
            new_name='FIRST_NAME',
        ),
        migrations.RenameField(
            model_name='driveapplication',
            old_name='student',
            new_name='FIRST_NAME',
        ),
        migrations.AlterUniqueTogether(
            name='activityapplication',
            unique_together={('title', 'FIRST_NAME')},
        ),
        migrations.AlterUniqueTogether(
            name='driveapplication',
            unique_together={('title', 'FIRST_NAME')},
        ),
    ]
