# Generated by Django 4.2.5 on 2024-03-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_alter_activity_reference_no'),
        ('users', '0017_rename_first_name_activityapplication_prn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driveapplication',
            old_name='drive_id',
            new_name='drive',
        ),
        migrations.RenameField(
            model_name='driveapplication',
            old_name='PRN',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='driveapplication',
            unique_together={('drive', 'student')},
        ),
    ]
