# Generated by Django 4.2.5 on 2024-03-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_coordinator_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='resume_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
