# Generated by Django 4.2.5 on 2024-03-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_driveapplication_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveapplication',
            name='resume_link',
        ),
    ]
