# Generated by Django 4.2.5 on 2024-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_drive_resume_link'),
        ('users', '0021_remove_driveapplication_resume_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityapplication',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='activityapplication',
            old_name='PRN',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='activityapplication',
            unique_together={('activity', 'student')},
        ),
    ]
