# Generated by Django 4.2.5 on 2024-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_activity_id_activityapplication_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Placement_type',
            field=models.CharField(blank=True, choices=[('On-campus', 'On-campus'), ('Off-campus', 'Off-campus')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major_projects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_projects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Dead_backlogs',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Yes')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Live_backlogs',
            field=models.PositiveIntegerField(blank=True, choices=[('N', 'No'), ('Y', 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pass_out_Year',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Placed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_gap',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('1', '1')], max_length=255, null=True),
        ),
    ]
