# Generated by Django 4.2.5 on 2024-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_student_company_name_student_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dead_backlogs',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Yes')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Live_backlogs',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Yes')], max_length=25, null=True),
        ),
    ]
