# Generated by Django 4.2.5 on 2024-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_student_dead_backlogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dead_backlogs',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Live_backlogs',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Placed',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20, null=True),
        ),
    ]
