# Generated by Django 4.2.5 on 2024-04-05 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_student_dead_backlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_details', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinators', models.ManyToManyField(to='users.coordinator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
