# Generated by Django 4.2.5 on 2024-04-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profileeditrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileEditRequest',
        ),
    ]
