# Generated by Django 4.2.5 on 2024-04-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_profilechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechange',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
