# Generated by Django 4.2.5 on 2024-04-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profilechange_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechange',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_approved', to='users.coordinator'),
        ),
    ]
