# Generated by Django 4.2.5 on 2024-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_profilechange_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveapplication',
            name='round1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='round2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='round3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='round4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='round5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driveapplication',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
