# Generated by Django 4.2.5 on 2024-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_driveapplication_round1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ALT_Mobile_NO',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='MOBILE_NO',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
