# Generated by Django 4.2.5 on 2024-05-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_student_alt_mobile_no_alter_student_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='ALT_Mobile_NO',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='MOBILE_NO',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
