# Generated by Django 4.2.5 on 2024-05-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profilechange_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechange',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.coordinator'),
        ),
    ]
