# Generated by Django 4.2.5 on 2024-05-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profilechange_responded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechange',
            name='responded_by',
        ),
    ]
