# Generated by Django 4.2.5 on 2024-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_student_age_alter_student_alt_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Placed',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20, null=True),
        ),
    ]
