# Generated by Django 4.2.5 on 2024-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_student_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AGE',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='ALT_Mobile_NO',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Admission_Type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Dead_backlogs',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='GENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='LOCAL_ADDRS',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Languages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Live_backlogs',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='MOBILE_NO',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Native_Place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='PERM_ADDRS',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Pass_out_Year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Preference_1',
            field=models.CharField(choices=[('Job', 'Job'), ('Entrepreneurship', 'Entrepreneurship'), ('Higher Studies', 'Higher Studies')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Preference_2',
            field=models.CharField(choices=[('Job', 'Job'), ('Entrepreneurship', 'Entrepreneurship'), ('Higher Studies', 'Higher Studies')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Preference_3',
            field=models.CharField(choices=[('Job', 'Job'), ('Entrepreneurship', 'Entrepreneurship'), ('Higher Studies', 'Higher Studies')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_1_sgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_2_sgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_3_sgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='SEM_4_sgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='X_Percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='X_board',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='X_year_of_passing',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year_gap',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='major_projects',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor_projects',
            field=models.CharField(max_length=200),
        ),
    ]
