# Generated by Django 4.2.5 on 2024-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_student_age_alter_student_alt_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2001-10-02'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EMAIL',
            field=models.EmailField(default='02@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PERSONAL_EMAIL',
            field=models.EmailField(default='02@gmail.com', max_length=254, unique=True),
        ),
    ]
