# Generated by Django 4.2.5 on 2024-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_student_dob_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EMAIL',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PERSONAL_EMAIL',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
