# Generated by Django 4.2.5 on 2024-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_drive_reference_no_drive_application_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
