# Generated by Django 4.2.5 on 2024-03-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_drive_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='Reference_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drive',
            name='application_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='shared_on_date',
            field=models.DateField(),
        ),
    ]
