# Generated by Django 4.2.5 on 2024-03-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_drive_reference_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='shared_on_date',
        ),
    ]
