# Generated by Django 4.2.5 on 2024-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_remove_drive_shared_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Reference_no',
            field=models.CharField(default='JNEC/TPO/ABC123', max_length=100),
        ),
    ]
