# Generated by Django 4.2.5 on 2024-03-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_alter_activity_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='resume_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
