# Generated by Django 4.2.5 on 2024-04-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_alter_drive_round_4_name_alter_drive_round_5_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='round_1_name',
            new_name='round1',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='round_2_name',
            new_name='round2',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='round_3_name',
            new_name='round3',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='round_4_name',
            new_name='round4',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='round_5_name',
            new_name='round5',
        ),
    ]
