# Generated by Django 4.2.5 on 2024-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0011_rename_round_1_name_drive_round1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='round1',
            field=models.CharField(blank=True, default='Round 1', max_length=100, null=True, verbose_name='Round 1 Name'),
        ),
    ]
