# Generated by Django 4.2.5 on 2024-05-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_alter_drive_round1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='selection_process',
            new_name='job_description',
        ),
    ]
