# Generated by Django 4.2.5 on 2024-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_rename_selection_process_drive_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='drive',
            name='application_last_date',
            field=models.DateField(default='2002-10-01'),
        ),
        migrations.AddField(
            model_name='drive',
            name='drive_status',
            field=models.CharField(choices=[('Terminated', 'Terminated'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10),
        ),
    ]
