# Generated by Django 4.2.5 on 2024-05-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0014_industrytype_drive_application_last_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryType',
        ),
    ]
