# Generated by Django 4.2.5 on 2024-05-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0015_delete_industrytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='application_last_date',
        ),
    ]
