# Generated by Django 4.2.5 on 2024-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0017_drive_application_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='application_last_date',
            field=models.DateField(default='2002-12-02'),
        ),
    ]
