# Generated by Django 4.2.5 on 2024-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0018_alter_drive_application_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('Terminated', 'Terminated'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10),
        ),
    ]
