# Generated by Django 4.2.5 on 2024-06-13 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0019_activity_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='Booklets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booklet', models.FileField(upload_to='booklets/')),
                ('company_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ManyToManyField(to='notices.department')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
