# Generated by Django 4.2.5 on 2024-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0021_booklets_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drive',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='booklets',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
