# Generated by Django 4.2.5 on 2024-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0022_alter_drive_options_alter_booklets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='drive',
            name='drive_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10),
        ),
    ]
